config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root to: "sentences#index"

	resources :users, only: [:show] do  #ユーザーページ
		resources :likes, only: [:index, :create, :destroy]  #あるユーザーのお気に入り一覧ページ
	end

	resources :sentences, only: [:index, :create, :edit, :destroy, :update] do  #TOPタイムライン、編集ページ
		collection do
			patch 'memorized' #覚えたボタン
			patch 'show_all' #全表示ボタン
			post 'copy' #コピーボタン
		end
		resources :likes, only: [:create, :destroy]
	end

	resources :folds, only: [:show, :create, :edit, :destroy] do
		# resources :words, only: [:index]
		get 'words'
		get 'words_c_to_j'
	end

	resources :words, only: [:edit, :update]

	# resources :word_folds, only: [:create, :edit] do
	# 	get 'j_to_c'
	# 	get 'c_to_j'
	# end

	put '/words_hide'      => 'words#hide'
	put '/words_show'      => 'words#show'
	put '/words_hide_c_to_j'      => 'words#hide_c_to_j'
	put '/words_show_c_to_j'      => 'words#show_c_to_j'


	resources :abouts, only: [:index] #サービス説明ページ

end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :sentence, counter_cache: :likes_count
	belongs_to :user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

	def index
    @user = User.find(params[:user_id])
    likes = @user.likes

    sentences = []
    likes.each do |like|
      sentence = like.sentence
      sentences << sentence
    end
    @sentences = Kaminari.paginate_array(sentences).page(params[:page]).per(20)

    @sentence = Sentence.new
    @sentence.words.build
    @fold = Fold.new
    @folds = @user.folds.active

    if user_signed_in?
      @myfolds = current_user.folds.active
    end

    @redirect_type = 2
    @redirect_id = params[:user_id]
	end

  def create
    like = Like.create(create_params)
    @sentence = Sentence.includes(:user).find(params[:sentence_id])
    @myfolds = current_user.folds.active
  end

  def destroy
    like = Like.find(params[:id])
    like.destroy
    @sentence = Sentence.includes(:user).find(params[:sentence_id])
  end


#############  ストロングパラメーター  ############
  private
  def create_params
    params.permit(:sentence_id).merge(user_id: current_user.id)
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if user_signed_in? %>

  <!-- likeが押されてるとき -->
  <% if sentence.like_user(current_user.id) %>


    <%= link_to sentence_like_path(sentence_id: sentence.id, id:like.id ), id: "unlike-button",method: :delete, remote: true do %>
      <span class="float-right">
        <%= sentence.likes_count %>
      </span>
      <%= render :partial => 'svg/like' %>
    <% end %>

    <div class="btn-group float-right">
      <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        <%= render :partial => 'svg/inbox' %>
      </button>
      <ul class="dropdown-menu">
        <% myfolds.each do |fold| %>
        <li>
          <%= link_to copy_sentences_path(fold: fold, sentence: sentence), method: :post, remote: true do %>
            <%= render :partial => 'svg/fold' %>
            <%= fold.name %>
          <% end %>
        </li>
        <% end %>
      </ul>
    </div>


  <!-- likeが押されてないとき -->
  <% else %>
    <%= link_to sentence_likes_path(sentence.id), id: "like-button", method: :post, remote: true do %>
      <span class="float-right">
        <%= sentence.likes_count %>
      </span>
      <%= render :partial => 'svg/not_like' %>
    <% end %>
  <% end %>
<% end %>

app/views/likes/create.js.erb
$("#like-buttons-<%= @sentence.id %>").html("<%= j(render :partial => 'likes/like', :locals=>{:sentence=>@sentence, :like => @sentence.likes.where(user_id: current_user.id).first, :myfolds=> @myfolds}) %>");

app/views/likes/destroy.js.erb
$("#like-buttons-<%= @sentence.id %>").html("<%= j(render :partial => 'likes/like', :locals=>{:sentence=>@sentence, :like => @sentence.likes.where(user_id: current_user.id).first}) %>");

app/views/likes/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8" >


      <!-- 文章一覧 -->
      <%= render :partial => 'sentences/sentences', :locals=>{ sentences: @sentences, myfolds: @myfolds} %>
    </div>
  </div>
</div>

<!-- ######## フッター ########## -->
<footer class="footer-navi">
  <div class="footer-left clearfix">

    <!-- ######## フォルダ ########## -->
    <div class="myfolds">
      <% if user_signed_in? %>
        <a data-placement="top" class='pop_folds' data-placement='above' title="フォルダを選択" href='#'>
          <%= render :partial => 'svg/folds' %>
        </a>
        <div id="pop_folds_wrapper" style="display: none">
          <div id="folds_list">
            <%= render :partial => 'folds/folds_list', :locals=>{myfolds: @myfolds} %>
          </div>
          <div class="create-fold">
            <%= form_for @fold, url: folds_path, method: :post, remote: true do |f| %>
              <%= f.text_field :name, placeholder: "新しいフォルダ", class: "", :required => true %>
              <%= button_tag( class: "no-css zero-space") do %>
                <%= render :partial => 'svg/plus' %>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>


    <!-- ######## 検索 ########## -->
<!--     <div class="search">
      <%= render :partial => 'svg/search' %>
    </div>
    <div class="search-input">
      <input name="keyword" placeholder="" type="text" value=""></input>
    </div> -->
  </div>


  <div class="footer-right clearfix">
    <!-- ######## 日中入れ替え ########## -->
<!--     <div class="replace">
      <%= render :partial => 'svg/replace' %>
    </div> -->

    <!-- ######## 文章作成ボタン ########## -->
    <div class="to-sentence-form">
      <% if user_signed_in? %>
      <!-- Button to Open the Modal -->
        <button type="button" class="no-css" data-toggle="modal" data-target="#sentence-create-modal">
          <%= render :partial => 'svg/pen' %>
        </button>
      <% end %>
    </div>
  </div>
</footer>


<!-- ######## 文章作成モーダル ########## -->
<% if user_signed_in? %>
  <div class="modal fade" id="sentence-create-modal">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">新しい文章を追加する</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
          <%= render :partial => 'sentences/sentence_form', :locals=>{sentence: @sentence, fold_id: @fold_id, myfolds: @myfolds} %>
        </div>
        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
        </div>
      </div>
    </div>
  </div>
<% end %>