config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root to: "sentences#index"

	resources :users, only: [:show] do  #ユーザーページ
		resources :likes, only: [:index, :create, :destroy]  #あるユーザーのお気に入り一覧ページ
	end

	resources :sentences, only: [:index, :create, :edit, :destroy, :update] do  #TOPタイムライン、編集ページ
		collection do
			patch 'memorized' #覚えたボタン
			patch 'show_all' #全表示ボタン
			post 'copy' #コピーボタン
		end
		resources :likes, only: [:create, :destroy]
	end

	resources :folds, only: [:show, :create, :edit, :destroy] do
		# resources :words, only: [:index]
		get 'words'
		get 'words_c_to_j'
	end

	resources :words, only: [:edit, :update]

	# resources :word_folds, only: [:create, :edit] do
	# 	get 'j_to_c'
	# 	get 'c_to_j'
	# end

	put '/words_hide'      => 'words#hide'
	put '/words_show'      => 'words#show'
	put '/words_hide_c_to_j'      => 'words#hide_c_to_j'
	put '/words_show_c_to_j'      => 'words#show_c_to_j'


	resources :abouts, only: [:index] #サービス説明ページ

end

app/models/word.rb
class Word < ApplicationRecord
	belongs_to :sentence
end

app/controllers/words_controller.rb
class WordsController < ApplicationController

	def edit
		@word = Word.find(params[:id])
		@redirect_flg = redirect_params
	end

	def update
		pin = PinYin.of_string(update_params[:ch], :unicode)
		if pin.count == 1
			pinyin = pin.first
		else
			pinyin = ""
			pin.each do |p|
				pinyin += "#{p} "
			end
		end

		word = Word.find(id_params)
		word.update("ja"=>update_params[:ja], "ch"=>update_params[:ch], "pin"=>pinyin)
		
		if redirect_params == "0"
			redirect_to fold_words_path(word.sentence.fold)
		else
			redirect_to fold_words_c_to_j_path(word.sentence.fold)
		end
	end

	def hide
		@word = Word.find(hide_params)
		@word.update(hide: 1)
	end

	def show
		@word = Word.find(hide_params)
		@word.update(hide: 0)
	end

	def hide_c_to_j
		@word = Word.find(hide_params)
		@word.update(hide_c_to_j: 1)
	end

	def show_c_to_j
		@word = Word.find(hide_params)
		@word.update(hide_c_to_j: 0)
	end


	private
  def hide_params
    params[:id]
  end

	def update_params
    params.require(:word)
	end
	
	def id_params
		params.require(:id)
	end

	def redirect_params
		params[:redirect_flg]
	end

end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_word_hide.html.erb
<% if word.hide == false %>
  <th><%= link_to "□", edit_word_path(word.id, redirect_flg: 0) %></th>
  <th><%= word.ja %></th>
  <th><%= word.ch %></th>
  <th><%= word.pin %></th>
  <th class="padding0" style="padding: 0;">
    <%= link_to words_hide_path(id: word.id), class: "word_hide_btn", method: :put, remote: true do %>
      ✔︎
    <% end %>
  </th>
<% else %>
  <th class="grey-col"><%= link_to "□", edit_word_path(word.id) %></th>
  <th class="grey-col"><%= word.ja %></th>
  <th class="grey-col"><%= word.ch %></th>
  <th class="grey-col"><%= word.pin %></th>
  <th class="padding0" style="padding: 0;">
    <%= link_to words_show_path(id: word.id), class: "word_hide_btn", method: :put, remote: true do %>
      ×
    <% end %>
  </th>
<% end %>

app/views/words/_word_hide_c_to_j.html.erb
<% if word.hide_c_to_j == false %>
  <th><%= link_to "□", edit_word_path(word.id, redirect_flg: 1) %></th>
  <th><%= word.ch %></th>
  <th><%= word.pin %></th>
  <th><%= word.ja %></th>
  <th class="padding0" style="padding: 0;">
    <%= link_to words_hide_c_to_j_path(id: word.id), class: "word_hide_btn", method: :put, remote: true do %>
      ✔︎
    <% end %>
  </th>
<% else %>
  <th class="grey-col"><%= link_to "□", edit_word_path(word.id, redirect_flg: 1) %></th>
  <th class="grey-col"><%= word.ch %></th>
  <th class="grey-col"><%= word.pin %></th>
  <th class="grey-col"><%= word.ja %></th>
  <th class="padding0" style="padding: 0;">
    <%= link_to words_show_c_to_j_path(id: word.id), class: "word_hide_btn", method: :put, remote: true do %>
      ×
    <% end %>
  </th>
<% end %>

app/views/words/edit.html.erb
<%= form_for @word, method: :patch do |w| %>
    <ul class="w-c">
		<%= w.text_field :ja, placeholder: "日本語", class: "w-c-ja", :required => true %>
		<%= w.text_field :ch, placeholder: "中国語", class: "w-c-ch", :required => true %>
	</div>

    <input name="redirect_flg" type="hidden" value="<%=@redirect_flg %>">

    <%= w.submit "更新", class: "" %>
<% end %>

app/views/words/hide.js.erb
$("#word_btn_<%= @word.id %>").html("<%= j(render :partial => 'words/word_hide', :locals=>{word: @word}) %>");

app/views/words/hide_c_to_j.js.erb
$("#word_btn_c_to_j_<%= @word.id %>").html("<%= j(render :partial => 'words/word_hide_c_to_j', :locals=>{word: @word}) %>");

app/views/words/show.js.erb
$("#word_btn_<%= @word.id %>").html("<%= j(render :partial => 'words/word_hide', :locals=>{word: @word}) %>");

app/views/words/show_c_to_j.js.erb
$("#word_btn_c_to_j_<%= @word.id %>").html("<%= j(render :partial => 'words/word_hide_c_to_j', :locals=>{word: @word}) %>");