config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root to: "sentences#index"

	resources :users, only: [:show] do  #ユーザーページ
		resources :likes, only: [:index, :create, :destroy]  #あるユーザーのお気に入り一覧ページ
	end

	resources :sentences, only: [:index, :create, :edit, :destroy, :update] do  #TOPタイムライン、編集ページ
		collection do
			patch 'memorized' #覚えたボタン
			patch 'show_all' #全表示ボタン
			post 'copy' #コピーボタン
		end
		resources :likes, only: [:create, :destroy]
	end

	resources :folds, only: [:show, :create, :edit, :destroy] do
		# resources :words, only: [:index]
		get 'words'
		get 'words_c_to_j'
	end

	resources :words, only: [:edit, :update]

	# resources :word_folds, only: [:create, :edit] do
	# 	get 'j_to_c'
	# 	get 'c_to_j'
	# end

	put '/words_hide'      => 'words#hide'
	put '/words_show'      => 'words#show'
	put '/words_hide_c_to_j'      => 'words#hide_c_to_j'
	put '/words_show_c_to_j'      => 'words#show_c_to_j'


	resources :abouts, only: [:index] #サービス説明ページ

end

app/models/fold.rb
class Fold < ApplicationRecord
	belongs_to :user
	has_many :sentences

	scope :active, -> { where(deleted: false) }
end

app/controllers/folds_controller.rb
class FoldsController < ApplicationController

	def show
		@sentence = Sentence.new
		@fold_id = params[:id]
		@sentence.words.build

		@current_fold = Fold.find(params[:id])
		@current_fold_user_id = @current_fold.user_id
		@user = User.find(@current_fold_user_id)
		@fold = Fold.new
		@myfolds = @user.folds.active

		@foldsentences = @current_fold.sentences.where(hide: 0).order("created_at DESC").page(params[:page]).per(20)

		@redirect_type = 3
		@redirect_id = params[:id]
	end

	def create
		Fold.create(create_params)
		@myfolds = current_user.folds.active
		@sentence = Sentence.new
		@sentence.words.build
		@sentences = Sentence.includes(:user).order("created_at DESC").page(params[:page]).per(20)
	end

	def edit

	end

	def destroy

	end

	def words
		@sentence = Sentence.new
		@fold_id = params[:id]
		@sentence.words.build

		@current_fold = Fold.find(params[:fold_id])
		@current_fold_user_id = @current_fold.user_id
		@user = User.find(@current_fold_user_id)
		@fold = Fold.new
		@myfolds = @user.folds.active

		@foldsentences = @current_fold.sentences.order("created_at DESC").includes(:words)

		@redirect_type = 3
		@redirect_id = params[:id]
	end

	def words_c_to_j
		@sentence = Sentence.new
		@fold_id = params[:id]
		@sentence.words.build

		@current_fold = Fold.find(params[:fold_id])
		@current_fold_user_id = @current_fold.user_id
		@user = User.find(@current_fold_user_id)
		@fold = Fold.new
		@myfolds = @user.folds.active

		@foldsentences = @current_fold.sentences.order("created_at DESC").includes(:words)

		@redirect_type = 3
		@redirect_id = params[:id]
	end


###############ストロングパラメーター#############
	private
	def create_params
		params.require(:fold).permit(:name).merge(user_id: current_user.id)
	end

end

app/helpers/folds_helper.rb
module FoldsHelper
end

app/views/folds/_fold_sentences.html.erb
<% sentences.each do |sentence| %>
	<div class="post">

		<!-- お気に入りボタン or 編集ボタン -->
		<div class="like-button">
			<% if user_signed_in? && sentence.user_id != current_user.id %>
				<div id="like-buttons-<%= sentence.id %>" class="btnplace">
					<%= render :partial => 'likes/like', :locals=>{sentence: sentence, like: sentence.likes.where(user_id: current_user.id).first, myfolds: myfolds} %>
				</div>
			<% end %>
			<% if user_signed_in? && sentence.user_id == current_user.id %>
				<%= link_to edit_sentence_path(sentence) do %>
					<%= render :partial => 'svg/edit' %>
				<% end %>
			<% end %>
		</div>

		<!-- left-sentence -->
		<div class="left-sentence-wrapper" style="float:left;">
			<% if sentence.user.image? %>
				<%= link_to user_path(sentence.user) do %>
					<%= image_tag sentence.user.image.thumb.url, :alt => "no-icon", :class => "icon" %>
				<% end %>
			<% else %>
				<%= link_to user_path(sentence.user) do %>
					<img class="icon" alt="no-icon" src="/images/no-icon.png">
				<% end %>
			<% end %>
			<p class="left_balloon"><%= sentence.ja %></p>
		</div>

		<!-- right-sentence -->
		<p class="right_balloon"><%= sentence.ch %></p>
		<p class="right_balloon"><%= sentence.pin %></p>
		<% unless sentence.words.first == nil %>
			<div class="right_balloon">
				<div>
					<button class="words-button" type="button" data-toggle="collapse" data-target="#words-open<%= sentence.id %>" aria-expanded="false" aria-controls="collapseExample">
						【単語帳を開く】
					</button>
					<div class="collapse" id="words-open<%= sentence.id %>">
						<div class="card card-body">
							<table class="table table-bordered table-responsive-sm">
								<thead>
									<tr>
										<th scope="col" >日本語</th>
										<th scope="col">中国語</th>
										<th scope="col">ピンイン</th>
									</tr>
								</thead>
								<tbody>
									<% sentence.words.each do |word| %>
										<tr>
											<th scope="col"><%= word.ja %></th>
											<th scope="col"><%= word.ch %></th>
											<th scope="col"><%= word.pin %></th>
										</tr>
									<% end %>
								</tbody>
							</table>
					  </div>
					</div>
				</div>
			</div>
		<% end %>
		<br class="clear_balloon"/>
	</div>
	<div class="memorized-button-place">
		<% if user_signed_in? && sentence.user_id == current_user.id %>
			<div id="memorized-buttons-<%= sentence.id %>" class="">
				<%= link_to memorized_sentences_path(sentence_id: sentence.id), id: "memorized-button",method: :patch, remote: true do %>
					覚えた！消えて！
				<% end %>
			</div>
		<% end %>
	</div>
	<div>
		<hr>
	</div>
<% end %>
<%= paginate sentences %>

app/views/folds/_fold_words.html.erb
<table class="table table-bordered table-responsive-sm">
	<thead>
		<tr>
			<th class="black-back white-col"></th>
			<th class="black-back white-col" >日本語</th>
			<th class="black-back white-col">中国語</th>
			<th class="black-back white-col">ピンイン</th>
			<th class="black-back white-col"></th>
		</tr>
	</thead>
	<tbody>
		<% sentences.each do |sentence| %>
			<% sentence.words.each do |word| %>
				<% if user_signed_in? && sentence.user_id == current_user.id %>
					<tr id="word_btn_<%= word.id %>">
						<%= render :partial => 'words/word_hide', :locals=>{word: word} %>
					</tr>
				<% end %>
			<% end %>
		<% end %>
	</tbody>
</table>

app/views/folds/_fold_words_c_to_j.html.erb
<table class="table table-bordered table-responsive-sm">
	<thead>
		<tr>
			<th class="black-back white-col"></th>
			<th class="black-back white-col">中国語</th>
			<th class="black-back white-col">ピンイン</th>
			<th class="black-back white-col" >日本語</th>
			<th class="black-back white-col"></th>
		</tr>
	</thead>
	<tbody>
		<% sentences.each do |sentence| %>
			<% sentence.words.each do |word| %>
				<% if user_signed_in? && sentence.user_id == current_user.id %>
					<tr id="word_btn_c_to_j_<%= word.id %>">
						<%= render :partial => 'words/word_hide_c_to_j', :locals=>{word: word} %>
					</tr>
				<% end %>
			<% end %>
		<% end %>
	</tbody>
</table>

app/views/folds/_folds_list.html.erb
<%= link_to user_likes_path(current_user) do %>
	<%= render :partial => 'svg/not_like_small' %>
	お気に入り
<% end %>
<% myfolds.each do |fold| %>
	<div class="folds-list">
		<% if current_page?(fold)  %>
			<%= render :partial => 'svg/fold_open' %>
			<%= fold.name %>
		<% else %>
			<a href="/folds/<%= fold.id %>">
			<%= render :partial => 'svg/fold' %>
			<%= fold.name %>
			</a>
		<% end %>
	</div>
<% end %>

app/views/folds/_folds_list_for_form.html.erb
<p>保存先フォルダを選ぶ</p>
<%= s.collection_select 'fold_id', myfolds, :id, :name,  {class: 'form-control'} %>

app/views/folds/_sentence_form_in_fold.html.erb
<%= form_for sentence, method: :post do |s| %>
<%= s.hidden_field :fold_id ,value: fold_id %>

<!-- リダイレクト先flg -->
	<%= s.hidden_field :redirect_id ,value: @redirect_id %>
	<%= s.hidden_field :redirect_type ,value: @redirect_type %>

	<div class="s-c-s">
		<%= s.text_area :ja, placeholder: "日本語文を書く", class: "s-c-ja", :required => true %>
		<%= s.text_area :ch, placeholder: "中国語文を書く", id: "chsentence", class: "s-c-ch", :required => true %>
	</div>
	<div id="auto-words" class="">
		<button type="button" class="btn btn-default">
			中国語の単語を抜き出す
	</button>
	<br><br>
	</div>


<!-- 単語フォーム -->
	<div class="form-group">
		<%= render :partial => "sentences/words_form", :locals=>{:s=>s} %>
			<button type="button" class="btn btn-default" data-toggle="collapse" data-target="#more-words">
				もっと単語を入れる
			</button>
		<div id="more-words" class="collapse">
			<div class="panel panel-default">
				<div class="panel-body">
					<%= render :partial => "folds/words_form", :locals=>{:s=>s} %>
					<%= render :partial => "folds/words_form", :locals=>{:s=>s} %>
					<%= render :partial => "folds/words_form", :locals=>{:s=>s} %>
					<%= render :partial => "folds/words_form", :locals=>{:s=>s} %>
					<%= render :partial => "folds/words_form", :locals=>{:s=>s} %>
					<%= render :partial => "folds/words_form", :locals=>{:s=>s} %>
					<%= render :partial => "folds/words_form", :locals=>{:s=>s} %>
				</div>
			</div>
		</div>
	</div>


<!-- フォルダ選択 -->
<!-- 	<hr>
	<div class="myfolds">
		<%= render :partial => "folds/folds_list_for_form", :locals=>{:s=>s, :myfolds=>myfolds} %>
	</div>
	<hr> -->
	<%= s.submit "作成", class: "", id: "sentence-create-button" %>
<% end %>

app/views/folds/create.js.erb
$("#folds_list").html("<%= j(render :partial => 'folds/folds_list', :locals=>{myfolds: @myfolds}) %>");
$("#sentence_form").html("<%= j(render :partial => 'sentences/sentence_form', :locals=>{sentence: @sentence, myfolds: @myfolds}) %>");
$("#sentneces-wrapper-for-fold-add").html("<%= j(render :partial => 'sentences/sentences', :locals=>{sentences: @sentences, myfolds: @myfolds}) %>");

app/views/folds/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8" >
      <br>
      <p style="text-align: center;">
        <strong><%= @current_fold.name %></strong>
      </p>
      <p class="right-align">
        <%= link_to "単語を勉強(日→中)", fold_words_path(@current_fold) %>
      </p>
      <p class="right-align">
        <%= link_to "単語を勉強(中→日)", fold_words_c_to_j_path(@current_fold) %>
      </p>
      <br>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8" >
      <div id="fold_posts">
        <%= render :partial => 'folds/fold_sentences', :locals=>{ sentences: @foldsentences, myfolds: @myfolds} %>
      </div>
    </div>
  </div>
</div>

<!-- ######## フッター ########## -->
<footer class="footer-navi">
  <div class="footer-left clearfix">

    <!-- ######## フォルダ ########## -->
    <div class="myfolds">
      <% if user_signed_in? %>
        <a data-placement="top" class='pop_folds' data-placement='above' title="フォルダを選択" href='#'>
          <%= render :partial => 'svg/folds' %>
        </a>
        <div id="pop_folds_wrapper" style="display: none">
          <div id="folds_list">
            <%= render :partial => 'folds/folds_list', :locals=>{myfolds: @myfolds} %>
          </div>
          <div class="create-fold">
            <%= form_for @fold, url: folds_path, method: :post, remote: true do |f| %>
              <%= f.text_field :name, placeholder: "新しいフォルダ", class: "", :required => true %>
              <%= button_tag( class: "no-css zero-space") do %>
                <%= render :partial => 'svg/plus' %>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>


    <!-- ######## 検索 ########## -->
<!--     <div class="search">
      <%= render :partial => 'svg/search' %>
    </div>
    <div class="search-input-infolds">
      <input name="keyword" placeholder="" type="text" value=""></input>
    </div> -->


    <!-- ######## 全部表示 ########## -->
    <% if user_signed_in? && @current_fold_user_id == current_user.id %>
      <div class="show_all_sentences">
        <%= link_to show_all_sentences_path(fold: @current_fold), id: "show-all-sentences-button",method: :patch do %>
          <%= render :partial => 'svg/show_all_sentences' %>
        <% end %>
      </div>
    <% end %>
  </div>


  <div class="footer-right clearfix">
    <!-- ######## 日中入れ替え ########## -->
<!--     <div class="replace">
      <%= render :partial => 'svg/replace' %>
    </div> -->

    <!-- ######## 文章作成ボタン ########## -->
    <div class="to-sentence-form">
      <% if user_signed_in? %>
      <!-- Button to Open the Modal -->
        <button type="button" class="no-css" data-toggle="modal" data-target="#sentence-create-modal">
          <%= render :partial => 'svg/pen' %>
        </button>
      <% end %>
    </div>
  </div>
</footer>


<!-- ######## 文章作成モーダル ########## -->
<% if user_signed_in? %>
  <div class="modal fade" id="sentence-create-modal">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">新しい文章を追加する</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
          <%= render :partial => 'folds/sentence_form_in_fold', :locals=>{sentence: @sentence, fold_id: @fold_id, myfolds: @myfolds} %>
        </div>
        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/folds/words.html.erb
<br>
<p style="text-align: center;"><strong><%= @current_fold.name %></strong></p>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8" >
      <div id="fold_posts">
        <div class="right-align">
          <%= link_to "中国語から勉強", fold_words_c_to_j_path(@current_fold) %>
        </div>
        <br>
        <%= render :partial => 'folds/fold_words', :locals=>{ sentences: @foldsentences, myfolds: @myfolds} %>
      </div>
    </div>
  </div>
</div>

<!-- ######## フッター ########## -->
<footer class="footer-navi">
  <div class="footer-left clearfix">

    <!-- ######## フォルダ ########## -->
    <div class="myfolds">
      <% if user_signed_in? %>
        <a data-placement="top" class='pop_folds' data-placement='above' title="フォルダを選択" href='#'>
          <%= render :partial => 'svg/folds' %>
        </a>
        <div id="pop_folds_wrapper" style="display: none">
          <div id="folds_list">
            <%= render :partial => 'folds/folds_list', :locals=>{myfolds: @myfolds} %>
          </div>
          <div class="create-fold">
            <%= form_for @fold, url: folds_path, method: :post, remote: true do |f| %>
              <%= f.text_field :name, placeholder: "新しいフォルダ", class: "", :required => true %>
              <%= button_tag( class: "no-css zero-space") do %>
                <%= render :partial => 'svg/plus' %>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

    <!-- ######## 全部表示 ########## -->
    <% if user_signed_in? && @current_fold_user_id == current_user.id %>
      <div class="show_all_sentences">
        <%= link_to show_all_sentences_path(fold: @current_fold), id: "show-all-sentences-button",method: :patch do %>
          <%= render :partial => 'svg/show_all_sentences' %>
        <% end %>
      </div>
    <% end %>
  </div>


  <div class="footer-right clearfix">
    <!-- ######## 日中入れ替え ########## -->
<!--     <div class="replace">
      <%= render :partial => 'svg/replace' %>
    </div> -->

    <!-- ######## 文章作成ボタン ########## -->
    <div class="to-sentence-form">
      <% if user_signed_in? %>
      <!-- Button to Open the Modal -->
        <button type="button" class="no-css" data-toggle="modal" data-target="#sentence-create-modal">
          <%= render :partial => 'svg/pen' %>
        </button>
      <% end %>
    </div>
  </div>
</footer>


<!-- ######## 文章作成モーダル ########## -->
<% if user_signed_in? %>
  <div class="modal fade" id="sentence-create-modal">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">新しい文章を追加する</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
          <%= render :partial => 'folds/sentence_form_in_fold', :locals=>{sentence: @sentence, fold_id: @fold_id, myfolds: @myfolds} %>
        </div>
        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/folds/words_c_to_j.html.erb
<br>
<p style="text-align: center;">
  <strong><%= link_to @current_fold.name, fold_path(@current_fold) %></strong>
</p>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8" >
      <div id="fold_posts">
        <div class="right-align">
          <%= link_to "日本語から勉強", fold_words_path(@current_fold) %>
        </div>
        <br>
        <%= render :partial => 'folds/fold_words_c_to_j', :locals=>{ sentences: @foldsentences, myfolds: @myfolds} %>
      </div>
    </div>
  </div>
</div>

<!-- ######## フッター ########## -->
<footer class="footer-navi">
  <div class="footer-left clearfix">

    <!-- ######## フォルダ ########## -->
    <div class="myfolds">
      <% if user_signed_in? %>
        <a data-placement="top" class='pop_folds' data-placement='above' title="フォルダを選択" href='#'>
          <%= render :partial => 'svg/folds' %>
        </a>
        <div id="pop_folds_wrapper" style="display: none">
          <div id="folds_list">
            <%= render :partial => 'folds/folds_list', :locals=>{myfolds: @myfolds} %>
          </div>
          <div class="create-fold">
            <%= form_for @fold, url: folds_path, method: :post, remote: true do |f| %>
              <%= f.text_field :name, placeholder: "新しいフォルダ", class: "", :required => true %>
              <%= button_tag( class: "no-css zero-space") do %>
                <%= render :partial => 'svg/plus' %>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

    <!-- ######## 全部表示 ########## -->
    <% if user_signed_in? && @current_fold_user_id == current_user.id %>
      <div class="show_all_sentences">
        <%= link_to show_all_sentences_path(fold: @current_fold), id: "show-all-sentences-button",method: :patch do %>
          <%= render :partial => 'svg/show_all_sentences' %>
        <% end %>
      </div>
    <% end %>
  </div>


  <div class="footer-right clearfix">
    <!-- ######## 日中入れ替え ########## -->
<!--     <div class="replace">
      <%= render :partial => 'svg/replace' %>
    </div> -->

    <!-- ######## 文章作成ボタン ########## -->
    <div class="to-sentence-form">
      <% if user_signed_in? %>
      <!-- Button to Open the Modal -->
        <button type="button" class="no-css" data-toggle="modal" data-target="#sentence-create-modal">
          <%= render :partial => 'svg/pen' %>
        </button>
      <% end %>
    </div>
  </div>
</footer>


<!-- ######## 文章作成モーダル ########## -->
<% if user_signed_in? %>
  <div class="modal fade" id="sentence-create-modal">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">新しい文章を追加する</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
          <%= render :partial => 'folds/sentence_form_in_fold', :locals=>{sentence: @sentence, fold_id: @fold_id, myfolds: @myfolds} %>
        </div>
        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
        </div>
      </div>
    </div>
  </div>
<% end %>